export const countries = [
  {
    label: 'Afghanistan',
    dialCode: '+93',
    value: 'AF',
    flag: '🇦🇫',
    native_name: 'افغانستان',
    currency: 'Afghan Afghani',
    currency_code: 'AFN',
    currency_symbol: '؋',
  },
  {
    label: 'Albania',
    dialCode: '+355',
    value: 'AL',
    flag: '🇦🇱',
    native_name: 'Shqipëria',
    currency: 'Albanian Lek',
    currency_code: 'ALL',
    currency_symbol: 'L',
  },
  {
    label: 'Algeria',
    dialCode: '+213',
    value: 'DZ',
    flag: '🇩🇿',
    native_name: 'Dzayer',
    currency: 'Algerian Dinar',
    currency_code: 'DZD',
    currency_symbol: 'د.ج',
  },
  {
    label: 'American Samoa',
    dialCode: '+1684',
    value: 'AS',
    flag: '🇦🇸',
    part_of: ['US'],
    currency: 'US Dollar',
    currency_code: 'USD',
    currency_symbol: '$',
  },
  {
    label: 'Andorra',
    dialCode: '+376',
    value: 'AD',
    flag: '🇦🇩',
    native_name: 'Andorra',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Angola',
    dialCode: '+244',
    value: 'AO',
    flag: '🇦🇴',
    native_name: 'Angola',
    currency: 'Angolan Kwanza',
    currency_code: 'AOA',
    currency_symbol: 'Kz',
  },
  {
    label: 'Anguilla',
    dialCode: '+1264',
    value: 'AI',
    flag: '🇦🇮',
    native_name: 'Anguilla',
    part_of: ['GB'],
    currency: 'East Caribbean Dollar',
    currency_code: 'XCD',
    currency_symbol: '$',
  },
  {
    label: 'Antarctica',
    dialCode: '+672',
    value: 'AQ',
    flag: '🇦🇶',
    currency: '',
    currency_code: '',
    currency_symbol: '',
  },
  {
    label: 'Antigua and Barbuda',
    dialCode: '+1268',
    value: 'AG',
    flag: '🇦🇬',
    native_name: 'Antigua and Barbuda',
    currency: 'East Caribbean Dollar',
    currency_code: 'XCD',
    currency_symbol: '$',
  },
  {
    label: 'Argentina',
    dialCode: '+54',
    value: 'AR',
    flag: '🇦🇷',
    native_name: 'Argentina',
    currency: 'Argentine Peso',
    currency_code: 'ARS',
    currency_symbol: '$',
  },
  {
    label: 'Armenia',
    dialCode: '+374',
    value: 'AM',
    flag: '🇦🇲',
    native_name: 'Հայաստան',
    currency: 'Armenian Dram',
    currency_code: 'AMD',
    currency_symbol: '֏',
  },
  {
    label: 'Aruba',
    dialCode: '+297',
    value: 'AW',
    flag: '🇦🇼',
    part_of: ['NL'],
    native_name: 'Aruba',
    currency: 'Aruban Florin',
    currency_code: 'AWG',
    currency_symbol: 'ƒ',
  },
  {
    label: 'Australia',
    dialCode: '+61',
    value: 'AU',
    preferred: true,
    flag: '🇦🇺',
    native_name: 'Australia',
    currency: 'Australian Dollar',
    currency_code: 'AUD',
    currency_symbol: '$',
  },
  {
    label: 'Austria',
    dialCode: '+43',
    value: 'AT',
    flag: '🇦🇹',
    native_name: 'Österreich',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Azerbaijan',
    dialCode: '+994',
    value: 'AZ',
    flag: '🇦🇿',
    native_name: 'Azərbaycan',
    currency: 'Azerbaijani Manat',
    currency_code: 'AZN',
    currency_symbol: '₼',
  },
  {
    label: 'Bahamas',
    dialCode: '+1242',
    value: 'BS',
    flag: '🇧🇸',
    native_name: 'The Bahamas',
    currency: 'Bahamian Dollar',
    currency_code: 'BSD',
    currency_symbol: '$',
  },
  {
    label: 'Bahrain',
    dialCode: '+973',
    value: 'BH',
    flag: '🇧🇭',
    native_name: 'البحرين',
    currency: 'Bahraini Dinar',
    currency_code: 'BHD',
    currency_symbol: '.د.ب',
  },
  {
    label: 'Bangladesh',
    dialCode: '+880',
    value: 'BD',
    flag: '🇧🇩',
    native_name: 'বাংলাদেশ',
    currency: 'Bangladeshi Taka',
    currency_code: 'BDT',
    currency_symbol: '৳',
  },
  {
    label: 'Barbados',
    dialCode: '+1246',
    value: 'BB',
    flag: '🇧🇧',
    native_name: 'Barbados',
    currency: 'Barbadian Dollar',
    currency_code: 'BBD',
    currency_symbol: '$',
  },
  {
    label: 'Belarus',
    dialCode: '+375',
    value: 'BY',
    flag: '🇧🇾',
    native_name: 'Беларусь',
    currency: 'Belarusian Ruble',
    currency_code: 'BYN',
    currency_symbol: 'Br',
  },
  {
    label: 'Belgium',
    dialCode: '+32',
    value: 'BE',
    flag: '🇧🇪',
    native_name: 'België',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Belize',
    dialCode: '+501',
    value: 'BZ',
    flag: '🇧🇿',
    native_name: 'Belize',
    currency: 'Belize Dollar',
    currency_code: 'BZD',
    currency_symbol: '$',
  },
  {
    label: 'Benin',
    dialCode: '+229',
    value: 'BJ',
    flag: '🇧🇯',
    native_name: 'Bénin',
    currency: 'West African CFA Franc',
    currency_code: 'XOF',
    currency_symbol: 'CFA',
  },
  {
    label: 'Bermuda',
    dialCode: '+1441',
    value: 'BM',
    flag: '🇧🇲',
    part_of: ['GB'],
    native_name: 'Bermuda',
    currency: 'Bermudian Dollar',
    currency_code: 'BMD',
    currency_symbol: '$',
  },
  {
    label: 'Bhutan',
    dialCode: '+975',
    value: 'BT',
    flag: '🇧🇹',
    native_name: 'འབྲུག་ཡུལ',
    currency: 'Bhutanese Ngultrum',
    currency_code: 'BTN',
    currency_symbol: 'Nu.',
  },
  {
    label: 'Bolivia, Plurinational State of',
    dialCode: '+591',
    value: 'BO',
    flag: '🇧🇴',
    native_name: 'Bolivia',
    currency: 'Bolivian Boliviano',
    currency_code: 'BOB',
    currency_symbol: 'Bs.',
  },
  {
    label: 'Bosnia and Herzegovina',
    dialCode: '+387',
    value: 'BA',
    flag: '🇧🇦',
    native_name: 'Bosna i Hercegovina',
    currency: 'Bosnia and Herzegovina Convertible Mark',
    currency_code: 'BAM',
    currency_symbol: 'KM',
  },
  {
    label: 'Botswana',
    dialCode: '+267',
    value: 'BW',
    flag: '🇧🇼',
    native_name: 'Botswana',
    currency: 'Botswana Pula',
    currency_code: 'BWP',
    currency_symbol: 'P',
  },
  {
    label: 'Brazil',
    dialCode: '+55',
    value: 'BR',
    flag: '🇧🇷',
    native_name: 'Brasil',
    currency: 'Brazilian Real',
    currency_code: 'BRL',
    currency_symbol: 'R$',
  },
  {
    label: 'British Indian Ocean Territory',
    dialCode: '+246',
    value: 'IO',
    flag: '🇮🇴',
    part_of: ['GB'],
    currency: 'US Dollar',
    currency_code: 'USD',
    currency_symbol: '$',
  },
  {
    label: 'Brunei Darussalam',
    dialCode: '+673',
    value: 'BN',
    flag: '🇧🇳',
    native_name: 'بروني',
    currency: 'Brunei Dollar',
    currency_code: 'BND',
    currency_symbol: '$',
  },
  {
    label: 'Bulgaria',
    dialCode: '+359',
    value: 'BG',
    flag: '🇧🇬',
    native_name: 'България',
    currency: 'Bulgarian Lev',
    currency_code: 'BGN',
    currency_symbol: 'лв',
  },
  {
    label: 'Burkina Faso',
    dialCode: '+226',
    value: 'BF',
    flag: '🇧🇫',
    native_name: 'Burkina Faso',
    currency: 'West African CFA Franc',
    currency_code: 'XOF',
    currency_symbol: 'CFA',
  },
  {
    label: 'Burundi',
    dialCode: '+257',
    value: 'BI',
    flag: '🇧🇮',
    native_name: 'Burundi',
    currency: 'Burundian Franc',
    currency_code: 'BIF',
    currency_symbol: 'FBu',
  },
  {
    label: 'Cambodia',
    dialCode: '+855',
    value: 'KH',
    flag: '🇰🇭',
    native_name: 'កម្ពុជា',
    currency: 'Cambodian Riel',
    currency_code: 'KHR',
    currency_symbol: '៛',
  },
  {
    label: 'Cameroon',
    dialCode: '+237',
    value: 'CM',
    flag: '🇨🇲',
    native_name: 'Cameroun',
    currency: 'Central African CFA Franc',
    currency_code: 'XAF',
    currency_symbol: 'FCFA',
  },
  {
    label: 'Canada',
    dialCode: '+1',
    value: 'CA',
    flag: '🇨🇦',
    native_name: 'Canada',
    currency: 'Canadian Dollar',
    currency_code: 'CAD',
    currency_symbol: '$',
  },
  {
    label: 'Cape Verde',
    dialCode: '+238',
    value: 'CV',
    flag: '🇨🇻',
    native_name: 'Cabo Verde',
    currency: 'Cape Verdean Escudo',
    currency_code: 'CVE',
    currency_symbol: '$',
  },
  {
    label: 'Cayman Islands',
    dialCode: '+345',
    value: 'KY',
    flag: '🇰🇾',
    part_of: ['GB'],
    native_name: 'Cayman Islands',
    currency: 'Cayman Islands Dollar',
    currency_code: 'KYD',
    currency_symbol: '$',
  },
  {
    label: 'Central African Republic',
    dialCode: '+236',
    value: 'CF',
    flag: '🇨🇫',
    native_name: 'République centrafricaine',
    currency: 'Central African CFA Franc',
    currency_code: 'XAF',
    currency_symbol: 'FCFA',
  },
  {
    label: 'Chad',
    dialCode: '+235',
    value: 'TD',
    flag: '🇹🇩',
    native_name: 'Tchad',
    currency: 'Central African CFA Franc',
    currency_code: 'XAF',
    currency_symbol: 'FCFA',
  },
  {
    label: 'Chile',
    dialCode: '+56',
    value: 'CL',
    flag: '🇨🇱',
    native_name: 'Chile',
    currency: 'Chilean Peso',
    currency_code: 'CLP',
    currency_symbol: '$',
  },
  {
    label: 'China',
    dialCode: '+86',
    value: 'CN',
    flag: '🇨🇳',
    native_name: '中国',
    currency: 'Chinese Yuan',
    currency_code: 'CNY',
    currency_symbol: '¥',
  },
  {
    label: 'Christmas Island',
    dialCode: '+61',
    value: 'CX',
    flag: '🇨🇽',
    part_of: ['AU'],
    native_name: 'Christmas Island',
    currency: 'Australian Dollar',
    currency_code: 'AUD',
    currency_symbol: '$',
  },
  {
    label: 'Cocos (Keeling) Islands',
    dialCode: '+61',
    value: 'CC',
    flag: '🇨🇨',
    part_of: ['AU'],
    native_name: 'Cocos (Keeling) Islands',
    currency: 'Australian Dollar',
    currency_code: 'AUD',
    currency_symbol: '$',
  },
  {
    label: 'Colombia',
    dialCode: '+57',
    value: 'CO',
    flag: '🇨🇴',
    native_name: 'Colombia',
    currency: 'Colombian Peso',
    currency_code: 'COP',
    currency_symbol: '$',
  },
  {
    label: 'Comoros',
    dialCode: '+269',
    value: 'KM',
    flag: '🇰🇲',
    native_name: 'جزر القمر',
    currency: 'Comorian Franc',
    currency_code: 'KMF',
    currency_symbol: 'CF',
  },
  {
    label: 'Congo',
    dialCode: '+242',
    value: 'CG',
    flag: '🇨🇬',
    native_name: 'République du Congo',
    currency: 'Central African CFA Franc',
    currency_code: 'XAF',
    currency_symbol: 'FCFA',
  },
  {
    label: 'Congo, The Democratic Republic of the',
    dialCode: '+243',
    value: 'CD',
    flag: '🇨🇩',
    native_name: 'République démocratique du Congo',
    currency: 'Congolese Franc',
    currency_code: 'CDF',
    currency_symbol: 'FC',
  },
  {
    label: 'Cook Islands',
    dialCode: '+682',
    value: 'CK',
    flag: '🇨🇰',
    native_name: 'Cook Islands',
    currency: 'New Zealand Dollar',
    currency_code: 'NZD',
    currency_symbol: '$',
  },
  {
    label: 'Costa Rica',
    dialCode: '+506',
    value: 'CR',
    flag: '🇨🇷',
    native_name: 'Costa Rica',
    currency: 'Costa Rican Colón',
    currency_code: 'CRC',
    currency_symbol: '₡',
  },
  {
    label: "Cote d'Ivoire",
    dialCode: '+225',
    value: 'CI',
    flag: '🇨🇮',
    native_name: "Côte d'Ivoire",
    currency: 'West African CFA Franc',
    currency_code: 'XOF',
    currency_symbol: 'CFA',
  },
  {
    label: 'Croatia',
    dialCode: '+385',
    value: 'HR',
    flag: '🇭🇷',
    native_name: 'Hrvatska',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Cuba',
    dialCode: '+53',
    value: 'CU',
    flag: '🇨🇺',
    native_name: 'Cuba',
    currency: 'Cuban Peso',
    currency_code: 'CUP',
    currency_symbol: '$',
  },
  {
    label: 'Curaçao',
    dialCode: '+599',
    value: 'CW',
    flag: '🇨🇼',
    part_of: ['NL'],
    native_name: 'Curaçao',
    currency: 'Netherlands Antillean Guilder',
    currency_code: 'ANG',
    currency_symbol: 'ƒ',
  },
  {
    label: 'Cyprus',
    dialCode: '+357',
    value: 'CY',
    flag: '🇨🇾',
    native_name: 'Κύπρος',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Czechia',
    dialCode: '+420',
    value: 'CZ',
    flag: '🇨🇿',
    native_name: 'Česko',
    currency: 'Czech Koruna',
    currency_code: 'CZK',
    currency_symbol: 'Kč',
  },
  {
    label: 'Canary Islands',
    dialCode: '+34',
    value: 'IC',
    flag: '🇮🇨',
    part_of: ['ES'],
    native_name: 'Islas Canarias',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Denmark',
    dialCode: '+45',
    value: 'DK',
    flag: '🇩🇰',
    native_name: 'Danmark',
    currency: 'Danish Krone',
    currency_code: 'DKK',
    currency_symbol: 'kr',
  },
  {
    label: 'Djibouti',
    dialCode: '+253',
    value: 'DJ',
    flag: '🇩🇯',
    native_name: 'جيبوتي',
    currency: 'Djiboutian Franc',
    currency_code: 'DJF',
    currency_symbol: 'Fdj',
  },
  {
    label: 'Dominica',
    dialCode: '+1767',
    value: 'DM',
    flag: '🇩🇲',
    native_name: 'Dominica',
    currency: 'East Caribbean Dollar',
    currency_code: 'XCD',
    currency_symbol: '$',
  },
  {
    label: 'Dominican Republic',
    dialCode: '+1849',
    value: 'DO',
    flag: '🇩🇴',
    native_name: 'República Dominicana',
    currency: 'Dominican Peso',
    currency_code: 'DOP',
    currency_symbol: '$',
    country_value: '+1',
    area_values: ['849', '829', '809'],
  },
  {
    label: 'Dominican Republic',
    dialCode: '+1829',
    value: 'DO',
    flag: '🇩🇴',
    secondary: true,
    native_name: 'República Dominicana',
    currency: 'Dominican Peso',
    currency_code: 'DOP',
    currency_symbol: '$',
  },
  {
    label: 'Dominican Republic',
    dialCode: '+1809',
    value: 'DO',
    flag: '🇩🇴',
    secondary: true,
    native_name: 'República Dominicana',
    currency: 'Dominican Peso',
    currency_code: 'DOP',
    currency_symbol: '$',
  },
  {
    label: 'Ecuador',
    dialCode: '+593',
    value: 'EC',
    flag: '🇪🇨',
    native_name: 'Ecuador',
    currency: 'US Dollar',
    currency_code: 'USD',
    currency_symbol: '$',
  },
  {
    label: 'Egypt',
    dialCode: '+20',
    value: 'EG',
    flag: '🇪🇬',
    native_name: 'مصر',
    currency: 'Egyptian Pound',
    currency_code: 'EGP',
    currency_symbol: 'E£',
  },
  {
    label: 'El Salvador',
    dialCode: '+503',
    value: 'SV',
    flag: '🇸🇻',
    native_name: 'El Salvador',
    currency: 'US Dollar',
    currency_code: 'USD',
    currency_symbol: '$',
  },
  {
    label: 'Equatorial Guinea',
    dialCode: '+240',
    value: 'GQ',
    flag: '🇬🇶',
    native_name: 'Guinea Ecuatorial',
    currency: 'Central African CFA Franc',
    currency_code: 'XAF',
    currency_symbol: 'FCFA',
  },
  {
    label: 'Eritrea',
    dialCode: '+291',
    value: 'ER',
    flag: '🇪🇷',
    native_name: 'ኤርትራ',
    currency: 'Eritrean Nakfa',
    currency_code: 'ERN',
    currency_symbol: 'Nfk',
  },
  {
    label: 'Estonia',
    dialCode: '+372',
    value: 'EE',
    flag: '🇪🇪',
    native_name: 'Eesti',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Eswatini',
    dialCode: '+268',
    value: 'SZ',
    flag: '🇸🇿',
    native_name: 'eSwatini',
    currency: 'Swazi Lilangeni',
    currency_code: 'SZL',
    currency_symbol: 'L',
  },
  {
    label: 'Ethiopia',
    dialCode: '+251',
    value: 'ET',
    flag: '🇪🇹',
    native_name: 'ኢትዮጵያ',
    currency: 'Ethiopian Birr',
    currency_code: 'ETB',
    currency_symbol: 'Br',
  },
  {
    label: 'Falkland Islands (Malvinas)',
    dialCode: '+500',
    value: 'FK',
    flag: '🇫🇰',
    part_of: ['GB'],
    native_name: 'Falkland Islands',
    currency: 'Falkland Islands Pound',
    currency_code: 'FKP',
    currency_symbol: '£',
  },
  {
    label: 'Faroe Islands',
    dialCode: '+298',
    value: 'FO',
    flag: '🇫🇴',
    part_of: ['DK'],
    native_name: 'Føroyar',
    currency: 'Faroese Króna',
    currency_code: 'DKK',
    currency_symbol: 'kr',
  },
  {
    label: 'Fiji',
    dialCode: '+679',
    value: 'FJ',
    flag: '🇫🇯',
    native_name: 'Fiji',
    currency: 'Fijian Dollar',
    currency_code: 'FJD',
    currency_symbol: '$',
  },
  {
    label: 'Finland',
    dialCode: '+358',
    value: 'FI',
    flag: '🇫🇮',
    native_name: 'Suomi',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'France',
    dialCode: '+33',
    value: 'FR',
    flag: '🇫🇷',
    native_name: 'France',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'French Guiana',
    dialCode: '+594',
    value: 'GF',
    flag: '🇬🇫',
    part_of: ['FR'],
    native_name: 'Guyane française',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'French Polynesia',
    dialCode: '+689',
    value: 'PF',
    flag: '🇵🇫',
    part_of: ['FR'],
    native_name: 'Polynésie française',
    currency: 'CFP Franc',
    currency_code: 'XPF',
    currency_symbol: '₣',
  },
  {
    label: 'French Southern Territories',
    dialCode: '+262',
    value: 'TF',
    flag: '🇹🇫',
    part_of: ['FR'],
    native_name: 'Terres australes françaises',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Gabon',
    dialCode: '+241',
    value: 'GA',
    flag: '🇬🇦',
    native_name: 'Gabon',
    currency: 'Central African CFA Franc',
    currency_code: 'XAF',
    currency_symbol: 'FCFA',
  },
  {
    label: 'Gambia',
    dialCode: '+220',
    value: 'GM',
    flag: '🇬🇲',
    native_name: 'The Gambia',
    currency: 'Gambian Dalasi',
    currency_code: 'GMD',
    currency_symbol: 'D',
  },
  {
    label: 'Georgia',
    dialCode: '+995',
    value: 'GE',
    flag: '🇬🇪',
    native_name: 'საქართველო',
    currency: 'Georgian Lari',
    currency_code: 'GEL',
    currency_symbol: '₾',
  },
  {
    label: 'Germany',
    dialCode: '+49',
    value: 'DE',
    flag: '🇩🇪',
    native_name: 'Deutschland',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Ghana',
    dialCode: '+233',
    value: 'GH',
    flag: '🇬🇭',
    native_name: 'Ghana',
    currency: 'Ghanaian Cedi',
    currency_code: 'GHS',
    currency_symbol: '₵',
  },
  {
    label: 'Gibraltar',
    dialCode: '+350',
    value: 'GI',
    flag: '🇬🇮',
    part_of: ['GB'],
    native_name: 'Gibraltar',
    currency: 'Gibraltar Pound',
    currency_code: 'GIP',
    currency_symbol: '£',
  },
  {
    label: 'Greece',
    dialCode: '+30',
    value: 'GR',
    flag: '🇬🇷',
    native_name: 'Ελλάς',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Greenland',
    dialCode: '+299',
    value: 'GL',
    flag: '🇬🇱',
    part_of: ['DK'],
    native_name: 'Kalaallit Nunaat',
    currency: 'Danish Krone',
    currency_code: 'DKK',
    currency_symbol: 'kr',
  },
  {
    label: 'Grenada',
    dialCode: '+1473',
    value: 'GD',
    flag: '🇬🇩',
    native_name: 'Grenada',
    currency: 'East Caribbean Dollar',
    currency_code: 'XCD',
    currency_symbol: '$',
  },
  {
    label: 'Guadeloupe',
    dialCode: '+590',
    value: 'GP',
    flag: '🇬🇵',
    part_of: ['FR'],
    native_name: 'Guadeloupe',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Guam',
    dialCode: '+1671',
    value: 'GU',
    flag: '🇬🇺',
    part_of: ['US'],
    native_name: 'Guam',
    currency: 'US Dollar',
    currency_code: 'USD',
    currency_symbol: '$',
  },
  {
    label: 'Guatemala',
    dialCode: '+502',
    value: 'GT',
    flag: '🇬🇹',
    native_name: 'Guatemala',
    currency: 'Guatemalan Quetzal',
    currency_code: 'GTQ',
    currency_symbol: 'Q',
  },
  {
    label: 'Guernsey',
    dialCode: '+44',
    value: 'GG',
    flag: '🇬🇬',
    part_of: ['GB'],
    native_name: 'Guernsey',
    currency: 'Guernsey Pound',
    currency_code: 'GGP',
    currency_symbol: '£',
  },
  {
    label: 'Guinea',
    dialCode: '+224',
    value: 'GN',
    flag: '🇬🇳',
    native_name: 'Guinée',
    currency: 'Guinean Franc',
    currency_code: 'GNF',
    currency_symbol: 'FG',
  },
  {
    label: 'Guinea-Bissau',
    dialCode: '+245',
    value: 'GW',
    flag: '🇬🇼',
    native_name: 'Guiné-Bissau',
    currency: 'West African CFA Franc',
    currency_code: 'XOF',
    currency_symbol: 'CFA',
  },
  {
    label: 'Guyana',
    dialCode: '+592',
    value: 'GY',
    flag: '🇬🇾',
    native_name: 'Guyana',
    currency: 'Guyanese Dollar',
    currency_code: 'GYD',
    currency_symbol: '$',
  },
  {
    label: 'Haiti',
    dialCode: '+509',
    value: 'HT',
    flag: '🇭🇹',
    native_name: 'Haïti',
    currency: 'Haitian Gourde',
    currency_code: 'HTG',
    currency_symbol: 'G',
  },
  {
    label: 'Heard & McDonald Islands',
    dialCode: '+672',
    value: 'HM',
    flag: '🇭🇲',
    part_of: ['AU'],
    native_name: 'Heard & McDonald Islands',
    currency: 'Australian Dollar',
    currency_code: 'AUD',
    currency_symbol: '$',
  },
  {
    label: 'Holy See (Vatican City State)',
    dialCode: '+379',
    value: 'VA',
    flag: '🇻🇦',
    native_name: 'Città del Vaticano',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Honduras',
    dialCode: '+504',
    value: 'HN',
    flag: '🇭🇳',
    native_name: 'Honduras',
    currency: 'Honduran Lempira',
    currency_code: 'HNL',
    currency_symbol: 'L',
  },
  {
    label: 'Hong Kong',
    dialCode: '+852',
    value: 'HK',
    flag: '🇭🇰',
    native_name: '香港',
    part_of: ['CN'],
    currency: 'Hong Kong Dollar',
    currency_code: 'HKD',
    currency_symbol: '$',
  },
  {
    label: 'Hungary',
    dialCode: '+36',
    value: 'HU',
    flag: '🇭🇺',
    native_name: 'Magyarország',
    currency: 'Hungarian Forint',
    currency_code: 'HUF',
    currency_symbol: 'Ft',
  },
  {
    label: 'Iceland',
    dialCode: '+354',
    value: 'IS',
    flag: '🇮🇸',
    native_name: 'Ísland',
    currency: 'Icelandic Króna',
    currency_code: 'ISK',
    currency_symbol: 'kr',
  },
  {
    label: 'India',
    dialCode: '+91',
    value: 'IN',
    preferred: true,
    flag: '🇮🇳',
    native_name: 'भारत',
    currency: 'Indian Rupee',
    currency_code: 'INR',
    currency_symbol: '₹',
  },
  {
    label: 'Indonesia',
    dialCode: '+62',
    value: 'ID',
    flag: '🇮🇩',
    native_name: 'Indonesia',
    currency: 'Indonesian Rupiah',
    currency_code: 'IDR',
    currency_symbol: 'Rp',
  },
  {
    label: 'Iran, Islamic Republic of',
    dialCode: '+98',
    value: 'IR',
    flag: '🇮🇷',
    native_name: 'ایران',
    currency: 'Iranian Rial',
    currency_code: 'IRR',
    currency_symbol: '﷼',
  },
  {
    label: 'Iraq',
    dialCode: '+964',
    value: 'IQ',
    flag: '🇮🇶',
    native_name: 'العراق',
    currency: 'Iraqi Dinar',
    currency_code: 'IQD',
    currency_symbol: 'ع.د',
  },
  {
    label: 'Ireland',
    dialCode: '+353',
    value: 'IE',
    flag: '🇮🇪',
    native_name: 'Éire',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Isle of Man',
    dialCode: '+44',
    value: 'IM',
    flag: '🇮🇲',
    part_of: ['GB'],
    native_name: 'Isle of Man',
    currency: 'Manx Pound',
    currency_code: 'IMP',
    currency_symbol: '£',
  },
  {
    label: 'Israel',
    dialCode: '+972',
    value: 'IL',
    flag: '🇮',
    native_name: 'ישראל',
    currency: 'Israeli New Shekel',
    currency_code: 'ILS',
    currency_symbol: '₪',
  },
  {
    label: 'Italy',
    dialCode: '+39',
    value: 'IT',
    flag: '🇮🇹',
    native_name: 'Italia',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Jamaica',
    dialCode: '+1876',
    value: 'JM',
    flag: '🇯🇲',
    native_name: 'Jamaica',
    currency: 'Jamaican Dollar',
    currency_code: 'JMD',
    currency_symbol: '$',
    country_value: '+1',
    area_values: ['876', '658'],
  },
  {
    label: 'Jamaica',
    dialCode: '+1658',
    value: 'JM',
    flag: '🇯🇲',
    secondary: true,
    native_name: 'Jamaica',
    currency: 'Jamaican Dollar',
    currency_code: 'JMD',
    currency_symbol: '$',
  },
  {
    label: 'Japan',
    dialCode: '+81',
    value: 'JP',
    flag: '🇯🇵',
    native_name: '日本',
    currency: 'Japanese Yen',
    currency_code: 'JPY',
    currency_symbol: '¥',
  },
  {
    label: 'Jersey',
    dialCode: '+44',
    value: 'JE',
    flag: '🇯🇪',
    part_of: ['GB'],
    native_name: 'Jersey',
    currency: 'Jersey Pound',
    currency_code: 'JEP',
    currency_symbol: '£',
  },
  {
    label: 'Jordan',
    dialCode: '+962',
    value: 'JO',
    flag: '🇯🇴',
    native_name: 'الأردن',
    currency: 'Jordanian Dinar',
    currency_code: 'JOD',
    currency_symbol: 'د.ا',
  },
  {
    label: 'Kazakhstan',
    dialCode: '+77',
    value: 'KZ',
    flag: '🇰🇿',
    native_name: 'Қазақстан',
    currency: 'Kazakhstani Tenge',
    currency_code: 'KZT',
    currency_symbol: '₸',
  },
  {
    label: 'Kenya',
    dialCode: '+254',
    value: 'KE',
    flag: '🇰🇪',
    native_name: 'Kenya',
    currency: 'Kenyan Shilling',
    currency_code: 'KES',
    currency_symbol: 'KSh',
  },
  {
    label: 'Kiribati',
    dialCode: '+686',
    value: 'KI',
    flag: '🇰🇮',
    native_name: 'Kiribati',
    currency: 'Australian Dollar',
    currency_code: 'AUD',
    currency_symbol: '$',
  },
  {
    label: "Korea, Democratic People's Republic of",
    dialCode: '+850',
    value: 'KP',
    flag: '🇰🇵',
    native_name: '조선민주주의인민공화국',
    currency: 'North Korean Won',
    currency_code: 'KPW',
    currency_symbol: '₩',
  },
  {
    label: 'Korea, Republic of',
    dialCode: '+82',
    value: 'KR',
    flag: '🇰🇷',
    native_name: '대한민국',
    currency: 'South Korean Won',
    currency_code: 'KRW',
    currency_symbol: '₩',
  },
  {
    label: 'Kuwait',
    dialCode: '+965',
    value: 'KW',
    flag: '🇰🇼',
    native_name: 'الكويت',
    currency: 'Kuwaiti Dinar',
    currency_code: 'KWD',
    currency_symbol: 'د.ك',
  },
  {
    label: 'Kyrgyzstan',
    dialCode: '+996',
    value: 'KG',
    flag: '🇰🇬',
    native_name: 'Кыргызстан',
    currency: 'Kyrgyzstani Som',
    currency_code: 'KGS',
    currency_symbol: 'с',
  },
  {
    label: 'Kosovo',
    dialCode: '+383',
    value: 'XK',
    flag: '🇽🇰',
    native_name: 'Kosova',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: "Lao People's Democratic Republic",
    dialCode: '+856',
    value: 'LA',
    flag: '🇱🇦',
    native_name: 'ປະເທດລາວ',
    currency: 'Lao Kip',
    currency_code: 'LAK',
    currency_symbol: '₭',
  },
  {
    label: 'Latvia',
    dialCode: '+371',
    value: 'LV',
    flag: '🇱🇻',
    native_name: 'Latvija',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Lebanon',
    dialCode: '+961',
    value: 'LB',
    flag: '🇱🇧',
    native_name: 'لبنان',
    currency: 'Lebanese Pound',
    currency_code: 'LBP',
    currency_symbol: 'ل.ل',
  },
  {
    label: 'Lesotho',
    dialCode: '+266',
    value: 'LS',
    flag: '🇱🇸',
    native_name: 'Lesotho',
    currency: 'Lesotho Loti',
    currency_code: 'LSL',
    currency_symbol: 'L',
  },
  {
    label: 'Liberia',
    dialCode: '+231',
    value: 'LR',
    flag: '🇱🇷',
    native_name: 'Liberia',
    currency: 'Liberian Dollar',
    currency_code: 'LRD',
    currency_symbol: '$',
  },
  {
    label: 'Libya',
    dialCode: '+218',
    value: 'LY',
    flag: '🇱🇾',
    native_name: 'ليبيا',
    currency: 'Libyan Dinar',
    currency_code: 'LYD',
    currency_symbol: 'ل.د',
  },
  {
    label: 'Liechtenstein',
    dialCode: '+423',
    value: 'LI',
    flag: '🇱🇮',
    native_name: 'Liechtenstein',
    currency: 'Swiss Franc',
    currency_code: 'CHF',
    currency_symbol: 'Fr.',
  },
  {
    label: 'Lithuania',
    dialCode: '+370',
    value: 'LT',
    flag: '🇱🇹',
    native_name: 'Lietuva',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Luxembourg',
    dialCode: '+352',
    value: 'LU',
    flag: '🇱🇺',
    native_name: 'Luxembourg',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Macao',
    dialCode: '+853',
    value: 'MO',
    flag: '🇲🇴',
    part_of: ['CN'],
    native_name: '澳門',
    currency: 'Macanese Pataca',
    currency_code: 'MOP',
    currency_symbol: 'MOP$',
  },
  {
    label: 'Madagascar',
    dialCode: '+261',
    value: 'MG',
    flag: '🇲🇬',
    native_name: 'Madagasikara',
    currency: 'Malagasy Ariary',
    currency_code: 'MGA',
    currency_symbol: 'Ar',
  },
  {
    label: 'Malawi',
    dialCode: '+265',
    value: 'MW',
    flag: '🇲🇼',
    native_name: 'Malawi',
    currency: 'Malawian Kwacha',
    currency_code: 'MWK',
    currency_symbol: 'MK',
  },
  {
    label: 'Malaysia',
    dialCode: '+60',
    value: 'MY',
    flag: '🇲🇾',
    native_name: 'Malaysia',
    currency: 'Malaysian Ringgit',
    currency_code: 'MYR',
    currency_symbol: 'RM',
  },
  {
    label: 'Maldives',
    dialCode: '+960',
    value: 'MV',
    flag: '🇲🇻',
    native_name: 'ދިވެހިރާއްޖެ',
    currency: 'Maldivian Rufiyaa',
    currency_code: 'MVR',
    currency_symbol: 'Rf',
  },
  {
    label: 'Mali',
    dialCode: '+223',
    value: 'ML',
    flag: '🇲🇱',
    native_name: 'Mali',
    currency: 'West African CFA Franc',
    currency_code: 'XOF',
    currency_symbol: 'CFA',
  },
  {
    label: 'Malta',
    dialCode: '+356',
    value: 'MT',
    flag: '🇲🇹',
    native_name: 'Malta',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Marshall Islands',
    dialCode: '+692',
    value: 'MH',
    flag: '🇲🇭',
    native_name: 'Marshall Islands',
    currency: 'US Dollar',
    currency_code: 'USD',
    currency_symbol: '$',
  },
  {
    label: 'Martinique',
    dialCode: '+596',
    value: 'MQ',
    flag: '🇲🇶',
    part_of: ['FR'],
    native_name: 'Martinique',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Mauritania',
    dialCode: '+222',
    value: 'MR',
    flag: '🇲🇷',
    native_name: 'موريتانيا',
    currency: 'Mauritanian Ouguiya',
    currency_code: 'MRU',
    currency_symbol: 'UM',
  },
  {
    label: 'Mauritius',
    dialCode: '+230',
    value: 'MU',
    flag: '🇲🇺',
    native_name: 'Moris',
    currency: 'Mauritian Rupee',
    currency_code: 'MUR',
    currency_symbol: '₨',
  },
  {
    label: 'Mayotte',
    dialCode: '+262',
    value: 'YT',
    flag: '🇾🇹',
    part_of: ['FR'],
    native_name: 'Mayotte',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Mexico',
    dialCode: '+52',
    value: 'MX',
    flag: '🇲🇽',
    native_name: 'México',
    currency: 'Mexican Peso',
    currency_code: 'MXN',
    currency_symbol: '$',
  },
  {
    label: 'Micronesia, Federated States of',
    dialCode: '+691',
    value: 'FM',
    flag: '🇫🇲',
    native_name: 'Micronesia',
    currency: 'US Dollar',
    currency_code: 'USD',
    currency_symbol: '$',
  },
  {
    label: 'Moldova, Republic of',
    dialCode: '+373',
    value: 'MD',
    flag: '🇲🇩',
    native_name: 'Moldova',
    currency: 'Moldovan Leu',
    currency_code: 'MDL',
    currency_symbol: 'L',
  },
  {
    label: 'Monaco',
    dialCode: '+377',
    value: 'MC',
    flag: '🇲🇨',
    native_name: 'Monaco',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Mongolia',
    dialCode: '+976',
    value: 'MN',
    flag: '🇲🇳',
    native_name: 'Монгол улс',
    currency: 'Mongolian Tögrög',
    currency_code: 'MNT',
    currency_symbol: '₮',
  },
  {
    label: 'Montenegro',
    dialCode: '+382',
    value: 'ME',
    flag: '🇲🇪',
    native_name: 'Crna Gora',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Montserrat',
    dialCode: '+1664',
    value: 'MS',
    flag: '🇲🇸',
    native_name: 'Montserrat',
    currency: 'East Caribbean Dollar',
    currency_code: 'XCD',
    currency_symbol: '$',
  },
  {
    label: 'Morocco',
    dialCode: '+212',
    value: 'MA',
    flag: '🇲🇦',
    native_name: 'المغرب',
    currency: 'Moroccan Dirham',
    currency_code: 'MAD',
    currency_symbol: 'د.م.',
  },
  {
    label: 'Mozambique',
    dialCode: '+258',
    value: 'MZ',
    flag: '🇲🇿',
    native_name: 'Moçambique',
    currency: 'Mozambican Metical',
    currency_code: 'MZN',
    currency_symbol: 'MT',
  },
  {
    label: 'Myanmar',
    dialCode: '+95',
    value: 'MM',
    flag: '🇲🇲',
    native_name: 'မြန်မာ',
    currency: 'Myanmar Kyat',
    currency_code: 'MMK',
    currency_symbol: 'K',
  },
  {
    label: 'Namibia',
    dialCode: '+264',
    value: 'NA',
    flag: '🇳🇦',
    native_name: 'Namibia',
    currency: 'Namibian Dollar',
    currency_code: 'NAD',
    currency_symbol: '$',
  },
  {
    label: 'Nauru',
    dialCode: '+674',
    value: 'NR',
    flag: '🇳🇷',
    native_name: 'Nauru',
    currency: 'Australian Dollar',
    currency_code: 'AUD',
    currency_symbol: '$',
  },
  {
    label: 'Nepal',
    dialCode: '+977',
    value: 'NP',
    flag: '🇳🇵',
    native_name: 'नेपाल',
    currency: 'Nepalese Rupee',
    currency_code: 'NPR',
    currency_symbol: '₨',
  },
  {
    label: 'Netherlands',
    dialCode: '+31',
    value: 'NL',
    flag: '🇳🇱',
    native_name: 'Nederland',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Caribbean Netherlands',
    dialCode: '+599',
    value: 'BQ',
    flag: '🇧🇶',
    part_of: ['NL'],
    native_name: 'Caribisch Nederland',
    currency: 'US Dollar',
    currency_code: 'USD',
    currency_symbol: '$',
  },
  {
    label: 'New Caledonia',
    dialCode: '+687',
    value: 'NC',
    flag: '🇳🇨',
    part_of: ['FR'],
    native_name: 'Nouvelle-Calédonie',
    currency: 'CFP Franc',
    currency_code: 'XPF',
    currency_symbol: '₣',
  },
  {
    label: 'New Zealand',
    dialCode: '+64',
    value: 'NZ',
    flag: '🇳🇿',
    native_name: 'New Zealand',
    currency: 'New Zealand Dollar',
    currency_code: 'NZD',
    currency_symbol: '$',
  },
  {
    label: 'Nicaragua',
    dialCode: '+505',
    value: 'NI',
    flag: '🇳🇮',
    native_name: 'Nicaragua',
    currency: 'Nicaraguan Córdoba',
    currency_code: 'NIO',
    currency_symbol: 'C$',
  },
  {
    label: 'Niger',
    dialCode: '+227',
    value: 'NE',
    flag: '🇳🇪',
    native_name: 'Niger',
    currency: 'West African CFA Franc',
    currency_code: 'XOF',
    currency_symbol: 'CFA',
  },
  {
    label: 'Nigeria',
    dialCode: '+234',
    value: 'NG',
    flag: '🇳🇬',
    native_name: 'Nigeria',
    currency: 'Nigerian Naira',
    currency_code: 'NGN',
    currency_symbol: '₦',
  },
  {
    label: 'Niue',
    dialCode: '+683',
    value: 'NU',
    flag: '🇳🇺',
    native_name: 'Niuē',
    currency: 'New Zealand Dollar',
    currency_code: 'NZD',
    currency_symbol: '$',
  },
  {
    label: 'Norfolk Island',
    dialCode: '+672',
    value: 'NF',
    flag: '🇳🇫',
    part_of: ['AU'],
    native_name: 'Norfolk Island',
    currency: 'Australian Dollar',
    currency_code: 'AUD',
    currency_symbol: '$',
  },
  {
    label: 'North Macedonia',
    dialCode: '+389',
    value: 'MK',
    flag: '🇲🇰',
    native_name: 'Северна Македонија',
    currency: 'Macedonian Denar',
    currency_code: 'MKD',
    currency_symbol: 'ден',
  },
  {
    label: 'Northern Mariana Islands',
    dialCode: '+1670',
    value: 'MP',
    flag: '🇲🇵',
    part_of: ['US'],
    native_name: 'Northern Mariana Islands',
    currency: 'US Dollar',
    currency_code: 'USD',
    currency_symbol: '$',
  },
  {
    label: 'Norway',
    dialCode: '+47',
    value: 'NO',
    flag: '🇳🇴',
    native_name: 'Norge',
    currency: 'Norwegian Krone',
    currency_code: 'NOK',
    currency_symbol: 'kr',
  },
  {
    label: 'Oman',
    dialCode: '+968',
    value: 'OM',
    flag: '🇴🇲',
    native_name: 'عُمان',
    currency: 'Omani Rial',
    currency_code: 'OMR',
    currency_symbol: 'ر.ع.',
  },
  {
    label: 'Pakistan',
    dialCode: '+92',
    value: 'PK',
    flag: '🇵🇰',
    native_name: 'پاکستان',
    currency: 'Pakistani Rupee',
    currency_code: 'PKR',
    currency_symbol: '₨',
  },
  {
    label: 'Palau',
    dialCode: '+680',
    value: 'PW',
    flag: '🇵🇼',
    native_name: 'Palau',
    currency: 'US Dollar',
    currency_code: 'USD',
    currency_symbol: '$',
  },
  {
    label: 'Palestine, State of',
    dialCode: '+970',
    value: 'PS',
    flag: '🇵🇸',
    native_name: 'فلسطين',
    currency: 'Israeli New Shekel',
    currency_code: 'ILS',
    currency_symbol: '₪',
  },
  {
    label: 'Panama',
    dialCode: '+507',
    value: 'PA',
    flag: '🇵🇦',
    native_name: 'Panamá',
    currency: 'Panamanian Balboa',
    currency_code: 'PAB',
    currency_symbol: 'B/.',
  },
  {
    label: 'Papua New Guinea',
    dialCode: '+675',
    value: 'PG',
    flag: '🇵🇬',
    native_name: 'Papua New Guinea',
    currency: 'Papua New Guinean Kina',
    currency_code: 'PGK',
    currency_symbol: 'K',
  },
  {
    label: 'Paraguay',
    dialCode: '+595',
    value: 'PY',
    flag: '🇵🇾',
    native_name: 'Paraguay',
    currency: 'Paraguayan Guaraní',
    currency_code: 'PYG',
    currency_symbol: '₲',
  },
  {
    label: 'Peru',
    dialCode: '+51',
    value: 'PE',
    flag: '🇵🇪',
    native_name: 'Perú',
    currency: 'Peruvian Sol',
    currency_code: 'PEN',
    currency_symbol: 'S/.',
  },
  {
    label: 'Philippines',
    dialCode: '+63',
    value: 'PH',
    flag: '🇵🇭',
    native_name: 'Pilipinas',
    currency: 'Philippine Peso',
    currency_code: 'PHP',
    currency_symbol: '₱',
  },
  {
    label: 'Pitcairn',
    dialCode: '+872',
    value: 'PN',
    flag: '🇵🇳',
    part_of: ['GB'],
    native_name: 'Pitcairn Islands',
    currency: 'New Zealand Dollar',
    currency_code: 'NZD',
    currency_symbol: '$',
  },
  {
    label: 'Poland',
    dialCode: '+48',
    value: 'PL',
    flag: '🇵🇱',
    native_name: 'Polska',
    currency: 'Polish Złoty',
    currency_code: 'PLN',
    currency_symbol: 'zł',
  },
  {
    label: 'Portugal',
    dialCode: '+351',
    value: 'PT',
    flag: '🇵🇹',
    native_name: 'Portugal',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Puerto Rico',
    dialCode: '+1939',
    value: 'PR',
    flag: '🇵🇷',
    country_value: '+1',
    area_values: ['939', '787'],
    part_of: ['US'],
    currency: 'US Dollar',
    currency_code: 'USD',
    currency_symbol: '$',
  },
  {
    label: 'Puerto Rico',
    dialCode: '+1787',
    value: 'PR',
    flag: '🇵🇷',
    secondary: true,
    part_of: ['US'],
    currency: 'US Dollar',
    currency_code: 'USD',
    currency_symbol: '$',
  },
  {
    label: 'Qatar',
    dialCode: '+974',
    value: 'QA',
    flag: '🇶🇦',
    native_name: 'قطر',
    currency: 'Qatari Riyal',
    currency_code: 'QAR',
    currency_symbol: 'ر.ق',
  },
  {
    label: 'Romania',
    dialCode: '+40',
    value: 'RO',
    flag: '🇷🇴',
    native_name: 'România',
    currency: 'Romanian Leu',
    currency_code: 'RON',
    currency_symbol: 'lei',
  },
  {
    label: 'Russia',
    dialCode: '+7',
    value: 'RU',
    flag: '🇷🇺',
    native_name: 'Россия',
    currency: 'Russian Ruble',
    currency_code: 'RUB',
    currency_symbol: '₽',
  },
  {
    label: 'Rwanda',
    dialCode: '+250',
    value: 'RW',
    flag: '🇷🇼',
    native_name: 'Rwanda',
    currency: 'Rwandan Franc',
    currency_code: 'RWF',
    currency_symbol: 'FRw',
  },
  {
    label: 'Réunion',
    dialCode: '+262',
    value: 'RE',
    flag: '🇷🇪',
    part_of: ['FR'],
    native_name: 'La Réunion',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Saint Barthélemy',
    dialCode: '+590',
    value: 'BL',
    flag: '🇧🇱',
    part_of: ['FR'],
    native_name: 'Saint-Barthélemy',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Saint Helena, Ascension and Tristan Da Cunha',
    dialCode: '+290',
    value: 'SH',
    flag: '🇸🇭',
    part_of: ['GB'],
    native_name: 'Saint Helena',
    currency: 'Saint Helena Pound',
    currency_code: 'SHP',
    currency_symbol: '£',
  },
  {
    label: 'Saint Kitts and Nevis',
    dialCode: '+1869',
    value: 'KN',
    flag: '🇰🇳',
    native_name: 'Saint Kitts and Nevis',
    currency: 'East Caribbean Dollar',
    currency_code: 'XCD',
    currency_symbol: '$',
  },
  {
    label: 'Saint Lucia',
    dialCode: '+1758',
    value: 'LC',
    flag: '🇱🇨',
    native_name: 'Saint Lucia',
    currency: 'East Caribbean Dollar',
    currency_code: 'XCD',
    currency_symbol: '$',
  },
  {
    label: 'Saint Martin',
    dialCode: '+590',
    value: 'MF',
    flag: '🇲🇫',
    part_of: ['FR'],
    native_name: 'Saint-Martin',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Saint Pierre and Miquelon',
    dialCode: '+508',
    value: 'PM',
    flag: '🇵🇲',
    part_of: ['FR'],
    native_name: 'Saint-Pierre-et-Miquelon',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Saint Vincent and the Grenadines',
    dialCode: '+1784',
    value: 'VC',
    flag: '🇻🇨',
    native_name: 'Saint Vincent and the Grenadines',
    currency: 'East Caribbean Dollar',
    currency_code: 'XCD',
    currency_symbol: '$',
  },
  {
    label: 'Samoa',
    dialCode: '+685',
    value: 'WS',
    flag: '🇼🇸',
    native_name: 'Samoa',
    currency: 'Samoan Tālā',
    currency_code: 'WST',
    currency_symbol: 'T',
  },
  {
    label: 'San Marino',
    dialCode: '+378',
    value: 'SM',
    flag: '🇸🇲',
    native_name: 'San Marino',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Sao Tome and Principe',
    dialCode: '+239',
    value: 'ST',
    flag: '🇸🇹',
    native_name: 'São Tomé e Príncipe',
    currency: 'São Tomé and Príncipe Dobra',
    currency_code: 'STN',
    currency_symbol: 'Db',
  },
  {
    label: 'Saudi Arabia',
    dialCode: '+966',
    value: 'SA',
    flag: '🇸🇦',
    native_name: 'المملكة العربية السعودية',
    currency: 'Saudi Riyal',
    currency_code: 'SAR',
    currency_symbol: 'ر.س',
  },
  {
    label: 'Senegal',
    dialCode: '+221',
    value: 'SN',
    flag: '🇸🇳',
    native_name: 'Sénégal',
    currency: 'West African CFA Franc',
    currency_code: 'XOF',
    currency_symbol: 'CFA',
  },
  {
    label: 'Serbia',
    dialCode: '+381',
    value: 'RS',
    flag: '🇷🇸',
    native_name: 'Србија',
    currency: 'Serbian Dinar',
    currency_code: 'RSD',
    currency_symbol: 'дин.',
  },
  {
    label: 'Seychelles',
    dialCode: '+248',
    value: 'SC',
    flag: '🇸🇨',
    native_name: 'Seychelles',
    currency: 'Seychellois Rupee',
    currency_code: 'SCR',
    currency_symbol: '₨',
  },
  {
    label: 'Sierra Leone',
    dialCode: '+232',
    value: 'SL',
    flag: '🇸🇱',
    native_name: 'Sierra Leone',
    currency: 'Sierra Leonean Leone',
    currency_code: 'SLL',
    currency_symbol: 'Le',
  },
  {
    label: 'Singapore',
    dialCode: '+65',
    value: 'SG',
    flag: '🇸🇬',
    native_name: 'Singapore',
    currency: 'Singapore Dollar',
    currency_code: 'SGD',
    currency_symbol: '$',
  },
  {
    label: 'Sint Maarten',
    dialCode: '+1721',
    value: 'SX',
    flag: '🇸🇽',
    part_of: ['NL'],
    native_name: 'Sint Maarten',
    currency: 'Netherlands Antillean Guilder',
    currency_code: 'ANG',
    currency_symbol: 'ƒ',
  },
  {
    label: 'Slovakia',
    dialCode: '+421',
    value: 'SK',
    flag: '🇸🇰',
    native_name: 'Slovensko',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Slovenia',
    dialCode: '+386',
    value: 'SI',
    flag: '🇸🇮',
    native_name: 'Slovenija',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Solomon Islands',
    dialCode: '+677',
    value: 'SB',
    flag: '🇸🇧',
    native_name: 'Solomon Islands',
    currency: 'Solomon Islands Dollar',
    currency_code: 'SBD',
    currency_symbol: '$',
  },
  {
    label: 'Somalia',
    dialCode: '+252',
    value: 'SO',
    flag: '🇸🇴',
    native_name: 'الصومال',
    currency: 'Somali Shilling',
    currency_code: 'SOS',
    currency_symbol: 'Sh.So.',
  },
  {
    label: 'South Africa',
    dialCode: '+27',
    value: 'ZA',
    flag: '🇿🇦',
    native_name: 'South Africa',
    currency: 'South African Rand',
    currency_code: 'ZAR',
    currency_symbol: 'R',
  },
  {
    label: 'South Georgia and the South Sandwich Islands',
    dialCode: '+500',
    value: 'GS',
    flag: '🇬🇸',
    part_of: ['GB'],
    native_name: 'South Georgia',
    currency: 'British Pound',
    currency_code: 'GBP',
    currency_symbol: '£',
  },
  {
    label: 'South Sudan',
    dialCode: '+211',
    value: 'SS',
    flag: '🇸🇸',
    native_name: 'South Sudan',
    currency: 'South Sudanese Pound',
    currency_code: 'SSP',
    currency_symbol: '£',
  },
  {
    label: 'Spain',
    dialCode: '+34',
    value: 'ES',
    flag: '🇪🇸',
    native_name: 'España',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
  {
    label: 'Sri Lanka',
    dialCode: '+94',
    value: 'LK',
    flag: '🇱🇰',
    native_name: 'ශ්‍රී ලංකාව',
    currency: 'Sri Lankan Rupee',
    currency_code: 'LKR',
    currency_symbol: '₨',
  },
  {
    label: 'Sudan',
    dialCode: '+249',
    value: 'SD',
    flag: '🇸🇩',
    native_name: 'السودان',
    currency: 'Sudanese Pound',
    currency_code: 'SDG',
    currency_symbol: 'ج.س.',
  },
  {
    label: 'Surilabel',
    dialCode: '+597',
    value: 'SR',
    flag: '🇸🇷',
    native_name: 'Surilabel',
    currency: 'Surilabelse Dollar',
    currency_code: 'SRD',
    currency_symbol: '$',
  },
  {
    label: 'Svalbard and Jan Mayen',
    dialCode: '+47',
    value: 'SJ',
    flag: '🇸🇯',
    part_of: ['NO'],
    native_name: 'Svalbard og Jan Mayen',
    currency: 'Norwegian Krone',
    currency_code: 'NOK',
    currency_symbol: 'kr',
  },
  {
    label: 'Sweden',
    dialCode: '+46',
    value: 'SE',
    flag: '🇸🇪',
    native_name: 'Sverige',
    currency: 'Swedish Krona',
    currency_code: 'SEK',
    currency_symbol: 'kr',
  },
  {
    label: 'Switzerland',
    dialCode: '+41',
    value: 'CH',
    flag: '🇨🇭',
    native_name: 'Schweiz',
    currency: 'Swiss Franc',
    currency_code: 'CHF',
    currency_symbol: 'Fr.',
  },
  {
    label: 'Syrian Arab Republic',
    dialCode: '+963',
    value: 'SY',
    flag: '🇸🇾',
    native_name: 'سورية',
    currency: 'Syrian Pound',
    currency_code: 'SYP',
    currency_symbol: '£S',
  },
  {
    label: 'Taiwan, Province of China',
    dialCode: '+886',
    value: 'TW',
    flag: '🇹🇼',
    native_name: '台灣',
    currency: 'New Taiwan Dollar',
    currency_code: 'TWD',
    currency_symbol: 'NT$',
  },
  {
    label: 'Tajikistan',
    dialCode: '+992',
    value: 'TJ',
    flag: '🇹🇯',
    native_name: 'Тоҷикистон',
    currency: 'Tajikistani Somoni',
    currency_code: 'TJS',
    currency_symbol: 'ЅМ',
  },
  {
    label: 'Tanzania, United Republic of',
    dialCode: '+255',
    value: 'TZ',
    flag: '🇹🇿',
    native_name: 'Tanzania',
    currency: 'Tanzanian Shilling',
    currency_code: 'TZS',
    currency_symbol: 'TSh',
  },
  {
    label: 'Thailand',
    dialCode: '+66',
    value: 'TH',
    flag: '🇹🇭',
    native_name: 'ประเทศไทย',
    currency: 'Thai Baht',
    currency_code: 'THB',
    currency_symbol: '฿',
  },
  {
    label: 'Timor-Leste',
    dialCode: '+670',
    value: 'TL',
    flag: '🇹🇱',
    native_name: 'Timor-Leste',
    currency: 'US Dollar',
    currency_code: 'USD',
    currency_symbol: '$',
  },
  {
    label: 'Togo',
    dialCode: '+228',
    value: 'TG',
    flag: '🇹🇬',
    native_name: 'Togo',
    currency: 'West African CFA Franc',
    currency_code: 'XOF',
    currency_symbol: 'CFA',
  },
  {
    label: 'Tokelau',
    dialCode: '+690',
    value: 'TK',
    flag: '🇹🇰',
    native_name: 'Tokelau',
    currency: 'New Zealand Dollar',
    currency_code: 'NZD',
    currency_symbol: '$',
  },
  {
    label: 'Tonga',
    dialCode: '+676',
    value: 'TO',
    flag: '🇹🇴',
    native_name: 'Tonga',
    currency: 'Tongan Paʻanga',
    currency_code: 'TOP',
    currency_symbol: 'T$',
  },
  {
    label: 'Trinidad and Tobago',
    dialCode: '+1868',
    value: 'TT',
    flag: '🇹🇹',
    native_name: 'Trinidad and Tobago',
    currency: 'Trinidad and Tobago Dollar',
    currency_code: 'TTD',
    currency_symbol: '$',
  },
  {
    label: 'Tunisia',
    dialCode: '+216',
    value: 'TN',
    flag: '🇹🇳',
    native_name: 'تونس',
    currency: 'Tunisian Dinar',
    currency_code: 'TND',
    currency_symbol: 'د.ت',
  },
  {
    label: 'Turkey',
    dialCode: '+90',
    value: 'TR',
    flag: '🇹🇷',
    native_name: 'Türkiye',
    currency: 'Turkish Lira',
    currency_code: 'TRY',
    currency_symbol: '₺',
  },
  {
    label: 'Türkiye',
    dialCode: '+90',
    value: 'TR',
    flag: '🇹🇷',
    native_name: 'Türkiye',
    currency: 'Turkish Lira',
    currency_code: 'TRY',
    currency_symbol: '₺',
    secondary: true,
  },
  {
    label: 'Turkmenistan',
    dialCode: '+993',
    value: 'TM',
    flag: '🇹🇲',
    native_name: 'Türkmenistan',
    currency: 'Turkmenistan Manat',
    currency_code: 'TMT',
    currency_symbol: 'm',
  },
  {
    label: 'Turks and Caicos Islands',
    dialCode: '+1649',
    value: 'TC',
    flag: '🇹🇨',
    part_of: ['GB'],
    native_name: 'Turks and Caicos Islands',
    currency: 'US Dollar',
    currency_code: 'USD',
    currency_symbol: '$',
  },
  {
    label: 'Tuvalu',
    dialCode: '+688',
    value: 'TV',
    flag: '🇹🇻',
    native_name: 'Tuvalu',
    currency: 'Australian Dollar',
    currency_code: 'AUD',
    currency_symbol: '$',
  },
  {
    label: 'Uganda',
    dialCode: '+256',
    value: 'UG',
    flag: '🇺🇬',
    native_name: 'Uganda',
    currency: 'Ugandan Shilling',
    currency_code: 'UGX',
    currency_symbol: 'USh',
  },
  {
    label: 'Ukraine',
    dialCode: '+380',
    value: 'UA',
    flag: '🇺🇦',
    native_name: 'Україна',
    currency: 'Ukrainian Hryvnia',
    currency_code: 'UAH',
    currency_symbol: '₴',
  },
  {
    label: 'United Arab Emirates',
    dialCode: '+971',
    value: 'AE',
    preferred: true,
    flag: '🇦🇪',
    native_name: 'الإمارات العربية المتحدة',
    currency: 'UAE Dirham',
    currency_code: 'AED',
    currency_symbol: 'د.إ',
  },
  {
    label: 'United Kingdom',
    dialCode: '+44',
    value: 'GB',
    preferred: true,
    flag: '🇬🇧',
    native_name: 'United Kingdom',
    currency: 'British Pound',
    currency_code: 'GBP',
    currency_symbol: '£',
  },
  {
    label: 'United States',
    dialCode: '+1',
    value: 'US',
    preferred: true,
    flag: '🇺🇸',
    native_name: 'United States',
    currency: 'US Dollar',
    currency_code: 'USD',
    currency_symbol: '$',
  },
  {
    label: 'Uruguay',
    dialCode: '+598',
    value: 'UY',
    flag: '🇺🇾',
    native_name: 'Uruguay',
    currency: 'Uruguayan Peso',
    currency_code: 'UYU',
    currency_symbol: '$',
  },
  {
    label: 'Uzbekistan',
    dialCode: '+998',
    value: 'UZ',
    flag: '🇺🇿',
    native_name: `O'zbekiston`,
    currency: 'Uzbekistani Som',
    currency_code: 'UZS',
    currency_symbol: `лв`,
  },
  {
    label: 'Vanuatu',
    dialCode: '+678',
    value: 'VU',
    flag: '🇻🇺',
    native_name: 'Vanuatu',
    currency: 'Vanuatu Vatu',
    currency_code: 'VUV',
    currency_symbol: 'VT',
  },
  {
    label: 'Venezuela, Bolivarian Republic of',
    dialCode: '+58',
    value: 'VE',
    flag: '🇻🇪',
    native_name: 'Venezuela',
    currency: 'Venezuelan Bolívar',
    currency_code: 'VES',
    currency_symbol: 'Bs.',
  },
  {
    label: 'Vietnam',
    dialCode: '+84',
    value: 'VN',
    flag: '🇻🇳',
    native_name: 'Việt Nam',
    currency: 'Vietlabelse Đồng',
    currency_code: 'VND',
    currency_symbol: '₫',
  },
  {
    label: 'Virgin Islands, British',
    dialCode: '+1284',
    value: 'VG',
    flag: '🇻🇬',
    part_of: ['GB'],
    native_name: 'British Virgin Islands',
    currency: 'US Dollar',
    currency_code: 'USD',
    currency_symbol: '$',
  },
  {
    label: 'Virgin Islands, U.S.',
    dialCode: '+1340',
    value: 'VI',
    flag: '🇻🇮',
    part_of: ['US'],
    native_name: 'U.S. Virgin Islands',
    currency: 'US Dollar',
    currency_code: 'USD',
    currency_symbol: '$',
  },
  {
    label: 'Wallis and Futuna',
    dialCode: '+681',
    value: 'WF',
    flag: '🇼🇫',
    native_name: 'Wallis-et-Futuna',
    currency: 'CFP Franc',
    currency_code: 'XPF',
    currency_symbol: '₣',
  },
  {
    label: 'Western Sahara',
    dialCode: '+212',
    value: 'EH',
    flag: '🇪🇭',
    native_name: 'الصحراء الغربية',
    currency: 'Moroccan Dirham',
    currency_code: 'MAD',
    currency_symbol: 'د.م.',
  },
  {
    label: 'Yemen',
    dialCode: '+967',
    value: 'YE',
    flag: '🇾🇪',
    native_name: 'اليمن',
    currency: 'Yemeni Rial',
    currency_code: 'YER',
    currency_symbol: '﷼',
  },
  {
    label: 'Zambia',
    dialCode: '+260',
    value: 'ZM',
    flag: '🇿🇲',
    native_name: 'Zambia',
    currency: 'Zambian Kwacha',
    currency_code: 'ZMW',
    currency_symbol: 'ZK',
  },
  {
    label: 'Zimbabwe',
    dialCode: '+263',
    value: 'ZW',
    flag: '🇿🇼',
    native_name: 'Zimbabwe',
    currency: 'US Dollar',
    currency_code: 'USD',
    currency_symbol: '$',
  },
  {
    label: 'Åland Islands',
    dialCode: '+358',
    value: 'AX',
    flag: '🇦🇽',
    part_of: ['FI'],
    native_name: 'Åland',
    currency: 'Euro',
    currency_code: 'EUR',
    currency_symbol: '€',
  },
];
